### PR TITLE
Vent Animation in Fog of War

### PR DESCRIPTION
**Pull request by Mr-Fluuff**
Added an Option to hide the animation of the vent when not in your vision

### CODE REVIEW

**Comment by Scoooom** [comment]
Hey @Mr-Fluuff, I would be happy to add this in.

However, would you mind adding an exception for the Engineer? If not I can do it myself. :)

**Comment by Mr-Fluuff** [comment]
Hmm that is an interesting idea. Maybe we add it as an additional option because some would like it and some wouldn't. Up to you

**Comment by Scoooom** [comment]
I'm always okay with settings! Just be careful not to overlap setting IDs. I've been sorta random so it isn't really consistent. Just search CUH for overlaps.

**Comment by Scoooom** [comment]
Also, could you submit a PR without the changes to README.md?

**Comment by Mr-Fluuff** [comment]
oh yes sorry I will do that tomorrow

**Comment by Mr-Fluuff** [comment]
does reverting the commit changes allow you to use this pull request? Sorry new to github pull requests

**Comment by Scoooom** [comment]
Yea that did :)

**Comment by Scoooom** [comment]
So, in my testing it seemed to disable the vent animation regardless of if it was in vision or not.

**Pull request merged**
